### PR TITLE
Looking for testing/feedback

### PR DESCRIPTION
**Pull request by tristan957**
Instead of continuing the back and forth, I just wanted to get my thoughts down in code.

### CODE REVIEW

**Comment by tristan957** [comment]
I got rid of the manual setup stuff. I think we should just add an equivalent of the following from the Remote extension.

image

**Comment by tristan957** [comment]
You may want to rebase on upstream main too.

**Comment by JCWasmx86** [comment]
Thanks for your PR. I now understand what you mean. This PR has to be rebased before it could be merged; the code looks fine. I will test it later as I have concerns about the UI, if the system is supported, the download fails due to missing binaries  (E.g. for linux distributions).

**Comment by JCWasmx86** [comment]
Could you please rebase your branch?

**Comment by tristan957** [comment]
Rebased. Haven't fixed the startup issue though.

**Comment by JCWasmx86** [comment]
I did look a bit more into it.

lsp/index.ts imports lsp/swift-mesonlsp.ts This one again imports `LanguageServerClient` from lsp/index.ts yielding a cyclic dependency.

I think one thing to solve this would be e.g. a lsp/common.ts that contains `create(server: LanguageServer, download: boolean, context: vscode.ExtensionContext): Promise<LanguageServerClient | null>`. This would break the graph from:

old

to

new

**Comment by JCWasmx86** [comment]
I made the changes myself here: https://github.com/mesonbuild/vscode-meson/commit/584270cce9ed2dd0e7c88db6ef6af8b6c8a80788

It looks fine to me, except this one issue:
If the user selects "Download", as it is a supported system, but there are no precompiled artifacts to download, it only shows "Failed to download the language server.". The error message should be more like: "The download failed due to $REASON", if there was e.g. a network error or URL 404s. But if there is no artifact, it should be more like "The language server supports your system, but provides no precompiled binaries/artifacts for your system. Set it up manually?" with a link to setup instructions

**Comment by tristan957** [comment]
Perhaps we just need another function that is different than supportsSystem that indicates whether the language server has a precompiled version for said system.

**Comment by JCWasmx86** [comment]
Shouldn't it be as simple as: `supportsSystem()` and `providesArtifacts()`, as you can either support a system and provide readily made artifacts to download or just support a system, but don't provide artifacts?

**Comment by tristan957** [comment]
Yes, that is what I meant.

**Comment by JCWasmx86** [comment]
Could you test with https://github.com/JCWasmx86/vscode-meson/commit/42c9e3347866d21b8d277379b0b93a03565ccc16 whether the browser is opening on a Linux system? For some reason `vscode.env.openExternal` does not do anything for me. (Regardless, if I `await` it or not, the same code worked before: https://github.com/mesonbuild/vscode-meson/pull/123/commits/e95a2dcfaa75e6c9bce55ac48708ecd3ade394b7#diff-04bba6a35cad1c794cbbe677678a51de13441b7a6ee8592b7b50be1f05c6f626R264)

**Comment by tristan957** [comment]
I don't think I have a way to test since I don't have a swift toolchain and their aren't Linux binaries.

**Comment by JCWasmx86** [comment]
What do you think is needed to get this PR merged? And then the one for upstream?

**Comment by tristan957** [comment]
Oh I thought you had said that you had edited my code and merged your changes already

**Comment by JCWasmx86** [comment]
Sadly it's a bit more complicated, sorry for the bad communication:

- I forked from mesonbuild/vscode-meson
- I made my changes on JCWasmx86/vscode-meson:main
- You forked from JCWasmx86/vscode-meson:main to tristan957/vscode-meson:lsp
- I took tristan957/vscode-meson:lsp and made changes in JCWasmx86/vscode-meson:lsp

That's the current status😅

**Comment by tristan957** [comment]
Oh so all that is "left" on this branch is the URI thing?

**Comment by JCWasmx86** [comment]
Yes, I can't figure out why this code here: https://github.com/JCWasmx86/vscode-meson/blob/42c9e3347866d21b8d277379b0b93a03565ccc16/src/lsp/common.ts#L31

does not open a browser, but this code does:

https://github.com/JCWasmx86/vscode-meson/blob/main/src/extension.ts#L261

**Comment by tristan957** [comment]
Have you inspected what setupURL is?

**Comment by JCWasmx86** [comment]
I was able to fix it, the setupURL I defined was undefined due to missing `static override` before it.

**Pull request merged**
